/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  pageType?: "about" | "contact" | "other";
  menuOrder?: number;
  content?: BlockContent;
  contactEmail?: string;
  contactPhone?: string;
};

export type BlockContent = Array<{
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "image";
  _key: string;
} | {
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  variant?: "plant" | "tool" | "remember" | "warning";
  title?: string;
  tip?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    } | {
      reference?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "post";
      } | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "plant";
      } | {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "category";
      };
      _type: "internalLink";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  _type: "tipBlock";
  _key: string;
} | {
  guide?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "guide";
  };
  showDescription?: boolean;
  displayMode?: "short" | "full" | "collapsed";
  _type: "relatedGuide";
  _key: string;
} | {
  post?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "post";
  };
  _type: "relatedPost";
  _key: string;
} | {
  title?: string;
  steps?: Array<{
    title?: string;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      } | {
        reference?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "post";
        } | {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "plant";
        } | {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "guide";
        };
        _type: "internalLink";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }>;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    };
    _type: "step";
    _key: string;
  }>;
  _type: "stepGuide";
  _key: string;
}>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    description?: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    description?: string;
    _type: "image";
    _key: string;
  }>;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  plantTypes?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "plantType";
  }>;
  plants?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "plant";
  }>;
  listText?: string;
  content?: BlockContent;
  relatedPosts?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "post";
  }>;
  relatedGuides?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "guide";
  }>;
  relatedPlants?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "plant";
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Guide = {
  _id: string;
  _type: "guide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  plantTypes?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "plantType";
  }>;
  plants?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "plant";
  }>;
  plantCategories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "plantCategory";
  }>;
  categories?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
  };
  steps?: Array<{
    title?: string;
    content?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      } | {
        reference?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "post";
        } | {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "plant";
        } | {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "guide";
        };
        _type: "internalLink";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    } | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
      _key: string;
    }>;
    image?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    };
    _type: "step";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    description?: string;
    _type: "image";
  };
};

export type Plant = {
  _id: string;
  _type: "plant";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  latinName?: string;
  slug?: Slug;
  description?: string;
  plantType?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "plantType";
  };
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    description?: string;
    _type: "image";
  };
  hardiness?: "Sone 1" | "Sone 2" | "Sone 3" | "Sone 4" | "Sone 5" | "Sone 6" | "Sone 7";
  seasons?: Array<string>;
  themes?: Array<string>;
  duration?: "Ett\xE5rig" | "Fler\xE5rig" | "To\xE5rig";
  flowering?: Array<string>;
  harvest?: Array<string>;
  allergyFriendly?: boolean;
  location?: "Full sol" | "Halvskygge" | "Skygge";
  soilType?: "Lett sandjord" | "Lett leirjord" | "Middels" | "Tung leirjord";
};

export type PlantType = {
  _id: string;
  _type: "plantType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  latinName?: string;
  slug?: Slug;
  plantCategory?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "plantCategory";
  };
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type PlantCategory = {
  _id: string;
  _type: "plantCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Page | BlockContent | Slug | Post | SanityImageCrop | SanityImageHotspot | Guide | Category | Plant | PlantType | PlantCategory | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: PAGES_QUERY
// Query: *[_type == "page"] | order(menuOrder asc) {    _id,    title,    slug,    pageType,    menuOrder  }
export type PAGES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  pageType: "about" | "contact" | "other" | null;
  menuOrder: number | null;
}>;
// Variable: PAGE_BY_SLUG_QUERY
// Query: *[_type == "page" && slug.current == $slug][0] {    _id,    title,    slug,    pageType,    menuOrder,    content,    contactEmail,    contactPhone  }
export type PAGE_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  pageType: "about" | "contact" | "other" | null;
  menuOrder: number | null;
  content: BlockContent | null;
  contactEmail: string | null;
  contactPhone: string | null;
} | null;
// Variable: POSTS_QUERY
// Query: *[_type == "post"] | order(_createdAt desc) {    _id,    title,    slug,    listText,    mainImage,    categories[]->{ _id, title, slug }  }
export type POSTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  listText: string | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    description?: string;
    _type: "image";
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
}>;
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && slug.current == $slug][0] {    _id,    title,    slug,    mainImage,    listText,    categories[]->{ _id, title, slug },    plants[]->{ _id, title, slug },    relatedPosts[]->{ _id, title, slug, mainImage, listText },    relatedGuides[]->{ _id, title, slug, description, image },    relatedPlants[]->{ _id, title, slug, image },    content[]{      ...,      _type == "relatedGuide" => {        ...,        guide->{          _id,          title,          slug,          description,          steps[]{            _key,            title,            content,            image          }        }      },      _type == "relatedPost" => {        ...,        post->{          _id,          title,          slug        }      },      // Ekspander interne lenker i marks      markDefs[]{        ...,        _type == "internalLink" => {          ...,          reference->{            _id,            _type,            title,            slug          }        }      }    }  }
export type POST_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    description?: string;
    _type: "image";
  } | null;
  listText: string | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
  plants: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
  }> | null;
  relatedPosts: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    mainImage: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      description?: string;
      _type: "image";
    } | null;
    listText: string | null;
  }> | null;
  relatedGuides: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    description: string | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "image";
    } | null;
  }> | null;
  relatedPlants: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    image: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      description?: string;
      _type: "image";
    } | null;
  }> | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }> | null;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
    markDefs: null;
  } | {
    guide: {
      _id: string;
      title: string | null;
      slug: Slug | null;
      description: string | null;
      steps: Array<{
        _key: string;
        title: string | null;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet";
          markDefs?: Array<{
            reference?: {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "guide";
            } | {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "plant";
            } | {
              _ref: string;
              _type: "reference";
              _weak?: boolean;
              [internalGroqTypeReferenceTo]?: "post";
            };
            _type: "internalLink";
            _key: string;
          } | {
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        } | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
          _key: string;
        }> | null;
        image: {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          caption?: string;
          _type: "image";
        } | null;
      }> | null;
    } | null;
    showDescription?: boolean;
    displayMode?: "collapsed" | "full" | "short";
    _type: "relatedGuide";
    _key: string;
    markDefs: null;
  } | {
    post: {
      _id: string;
      title: string | null;
      slug: Slug | null;
    } | null;
    _type: "relatedPost";
    _key: string;
    markDefs: null;
  } | {
    title?: string;
    steps?: Array<{
      title?: string;
      content?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal";
        listItem?: "bullet";
        markDefs?: Array<{
          reference?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "guide";
          } | {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "plant";
          } | {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "post";
          };
          _type: "internalLink";
          _key: string;
        } | {
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      } | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
        _key: string;
      }>;
      image?: {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        caption?: string;
        _type: "image";
      };
      _type: "step";
      _key: string;
    }>;
    _type: "stepGuide";
    _key: string;
    markDefs: null;
  } | {
    variant?: "plant" | "remember" | "tool" | "warning";
    title?: string;
    tip?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        reference?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "category";
        } | {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "plant";
        } | {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "post";
        };
        _type: "internalLink";
        _key: string;
      } | {
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "tipBlock";
    _key: string;
    markDefs: null;
  }> | null;
} | null;
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && count(*[_type == "post" && ^._id in categories[]._ref]) > 0] | order(_createdAt desc) {    _id,    title,    slug,    "postCount": count(*[_type == "post" && ^._id   in categories[]._ref])  }
export type CATEGORIES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  postCount: number;
}>;
// Variable: PLANTS_QUERY
// Query: *[_type == "plant"] | order(_createdAt desc) {    _id,    title,    slug,    image  }
export type PLANTS_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    description?: string;
    _type: "image";
  } | null;
}>;
// Variable: PLANTS_BY_SLUG_QUERY
// Query: *[_type == "plant" && plantType->slug.current == $slug] {  _id,  title,  slug,  mainImage,  "plantTypeTitle": plantType->title}
export type PLANTS_BY_SLUG_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: null;
  plantTypeTitle: string | null;
}>;
// Variable: PLANT_TYPES_QUERY
// Query: *[_type == "plantType" && count(*[_type ==        "plant" && plantType._ref == ^._id]) > 0] {         _id,                                              title,                                            slug,                                             description,                                      image,                                            "plantCount": count(*[_type == "plant" &&       plantType._ref == ^._id])                         }
export type PLANT_TYPES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  plantCount: number;
}>;
// Variable: PLANT_TYPE_BY_SLUG_QUERY
// Query: *[_type == "plantType" && plantCategory->slug.current == $slug][0] {  _id,  title,  slug,  mainImage,  "categoryTitle": plantCategory->title}
export type PLANT_TYPE_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: null;
  categoryTitle: string | null;
} | null;
// Variable: PLANT_TYPES_BY_SLUG_QUERY
// Query: *[_type == "plantType" && plantCategory->slug.current == $slug] {  _id,  title,  slug,  mainImage,  "categoryTitle": plantCategory->title}
export type PLANT_TYPES_BY_SLUG_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  mainImage: null;
  categoryTitle: string | null;
}>;
// Variable: PLANT_CATEGORY_QUERY
// Query: *[_type == "plantCategory" && count(                       *[_type == "plantType" && plantCategory._ref ==      ^._id &&                                                       count(*[_type == "plant" && plantType._ref ==      ^._id]) > 0                                                  ]                                                      ) > 0] {                                                   _id,                                                     title,                                                   slug,                                                    description,                                             image,                                                   "plantCount": count(                                       *[_type == "plantType" && plantCategory._ref ==    ^._id &&                                                         count(*[_type == "plant" && plantType._ref ==    ^._id]) > 0                                                    ]                                                      )                                                      }
export type PLANT_CATEGORY_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  plantCount: number;
}>;
// Variable: GUIDES_QUERY
// Query: *[_type == "guide"] | order(_createdAt desc) {    _id,    title,    slug,  }
export type GUIDES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;
// Variable: AARSHJUL_QUERY
// Query: *[_type == "plant" && (defined(seasons) || defined(flowering))] {    _id,    title,    slug,    image,    description,    seasons,    flowering,    harvest,    themes,    plantType->{ _id, title, slug }  }
export type AARSHJUL_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    description?: string;
    _type: "image";
  } | null;
  description: string | null;
  seasons: Array<string> | null;
  flowering: Array<string> | null;
  harvest: Array<string> | null;
  themes: Array<string> | null;
  plantType: {
    _id: string;
    title: string | null;
    slug: Slug | null;
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"page\"] | order(menuOrder asc) {\n    _id,\n    title,\n    slug,\n    pageType,\n    menuOrder\n  }\n": PAGES_QUERYResult;
    "\n  *[_type == \"page\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    pageType,\n    menuOrder,\n    content,\n    contactEmail,\n    contactPhone\n  }\n": PAGE_BY_SLUG_QUERYResult;
    "\n  *[_type == \"post\"] | order(_createdAt desc) {\n    _id,\n    title,\n    slug,\n    listText,\n    mainImage,\n    categories[]->{ _id, title, slug }\n  }\n": POSTS_QUERYResult;
    "\n  *[_type == \"post\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    mainImage,\n    listText,\n    categories[]->{ _id, title, slug },\n    plants[]->{ _id, title, slug },\n    relatedPosts[]->{ _id, title, slug, mainImage, listText },\n    relatedGuides[]->{ _id, title, slug, description, image },\n    relatedPlants[]->{ _id, title, slug, image },\n    content[]{\n      ...,\n      _type == \"relatedGuide\" => {\n        ...,\n        guide->{\n          _id,\n          title,\n          slug,\n          description,\n          steps[]{\n            _key,\n            title,\n            content,\n            image\n          }\n        }\n      },\n      _type == \"relatedPost\" => {\n        ...,\n        post->{\n          _id,\n          title,\n          slug\n        }\n      },\n      // Ekspander interne lenker i marks\n      markDefs[]{\n        ...,\n        _type == \"internalLink\" => {\n          ...,\n          reference->{\n            _id,\n            _type,\n            title,\n            slug\n          }\n        }\n      }\n    }\n  }\n": POST_BY_SLUG_QUERYResult;
    "\n  *[_type == \"category\" && count(*[_type == \"post\" && ^._id in categories[]._ref]) > 0] | order(_createdAt desc) {\n    _id,\n    title,\n    slug,\n    \"postCount\": count(*[_type == \"post\" && ^._id \n  in categories[]._ref])\n  }\n": CATEGORIES_QUERYResult;
    "\n  *[_type == \"plant\"] | order(_createdAt desc) {\n    _id,\n    title,\n    slug,\n    image\n  }\n": PLANTS_QUERYResult;
    "\n  *[_type == \"plant\" && plantType->slug.current == $slug] {\n  _id,\n  title,\n  slug,\n  mainImage,\n  \"plantTypeTitle\": plantType->title\n}\n": PLANTS_BY_SLUG_QUERYResult;
    "\n  *[_type == \"plantType\" && count(*[_type ==      \n  \"plant\" && plantType._ref == ^._id]) > 0] {     \n    _id,                                          \n    title,                                        \n    slug,                                         \n    description,                                  \n    image,                                        \n    \"plantCount\": count(*[_type == \"plant\" &&     \n  plantType._ref == ^._id])                       \n  }                                               \n": PLANT_TYPES_QUERYResult;
    "\n  *[_type == \"plantType\" && plantCategory->slug.current == $slug][0] {\n  _id,\n  title,\n  slug,\n  mainImage,\n  \"categoryTitle\": plantCategory->title\n}\n": PLANT_TYPE_BY_SLUG_QUERYResult;
    "\n  *[_type == \"plantType\" && plantCategory->slug.current == $slug] {\n  _id,\n  title,\n  slug,\n  mainImage,\n  \"categoryTitle\": plantCategory->title\n}\n": PLANT_TYPES_BY_SLUG_QUERYResult;
    "\n*[_type == \"plantCategory\" && count(                 \n      *[_type == \"plantType\" && plantCategory._ref ==    \n  ^._id &&                                               \n        count(*[_type == \"plant\" && plantType._ref ==    \n  ^._id]) > 0                                            \n      ]                                                  \n    ) > 0] {                                             \n      _id,                                               \n      title,                                             \n      slug,                                              \n      description,                                       \n      image,                                             \n      \"plantCount\": count(                               \n        *[_type == \"plantType\" && plantCategory._ref ==  \n  ^._id &&                                               \n          count(*[_type == \"plant\" && plantType._ref ==  \n  ^._id]) > 0                                            \n        ]                                                \n      )                                                  \n    }                                                       \n": PLANT_CATEGORY_QUERYResult;
    "\n  *[_type == \"guide\"] | order(_createdAt desc) {\n    _id,\n    title,\n    slug,\n  }\n": GUIDES_QUERYResult;
    "\n  *[_type == \"plant\" && (defined(seasons) || defined(flowering))] {\n    _id,\n    title,\n    slug,\n    image,\n    description,\n    seasons,\n    flowering,\n    harvest,\n    themes,\n    plantType->{ _id, title, slug }\n  }\n": AARSHJUL_QUERYResult;
  }
}
